export default {
    products: [
        {
            _id: '1',
            name: 'Jordan Why Not',
            image: '/images/d1.jpg',
            price: 50,
            brand: 'Nike',
            numReviews: 287,
            rating: 4.8,
            category: 'Nike',
            countInStock: 7,
            description: 'SHOES JORDAN, WHY NOT ZERO 0 BUY IN UKRAINE, ORIGINAL FROM AMERICA',
        },
        {
            _id: '2',
            name: 'Reabok Alen Iverson',
            image: '/images/d1.jpg',
            price: 60,
            brand: 'Reabok',
            numReviews: 83,
            rating: 4.4,
            category: 'Reabok',
            countInStock: 4,
            description: 'good2',
        },
        {
            _id: '3',
            name: 'Jordan Why Not',
            image: '/images/d1.jpg',
            price: 67,
            brand: 'Nike',
            numReviews: 283,
            rating: 4.0,
            category: 'Nike',
            countInStock: 0,
            description: 'SHOES JORDAN, WHY NOT ZERO 2.0 BUY IN UKRAINE, ORIGINAL FROM AMERICA',
        },
        {
            _id: '4',
            name: 'Jordan Why Not',
            image: '/images/d1.jpg',
            price: 50,
            brand: 'Nike',
            numReviews: 287,
            rating: 4.8,
            category: 'Nike',
            countInStock: 27,
            description: 'good4',
        },
        {
            _id: '5',
            name: 'Reabok Alen Iverson',
            image: '/images/d1.jpg',
            price: 60,
            brand: 'Reabok',
            numReviews: 83,
            rating: 4.4,
            category: 'Reabok',
            countInStock: 4,
        },
        {
            _id: '6',
            name: 'Jordan Why Not',
            image: '/images/d1.jpg',
            price: 67,
            brand: 'Nike',
            numReviews: 283,
            rating: 4.0,
            category: 'Nike',
            countInStock: 33,
        },
    ],
};
