export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOOVE_FROM_CART = 'REMOOVE_FROM_CART';
export const CART_SAVE_SHIPPNG = 'CART_SAVE_SHIPPNG';
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT'